name: Build and Publish container image to GitHub Container Registry

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    # - name: Convert repository name to lowercase
    #   id: repo-name-lowercase
    #   run: |
    #     repo_name=$(echo "${{ github.repository }}" | awk '{print tolower($0)}')
    #     echo "repo=$repo_name" >> $GITHUB_ENV

    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/ip-frontend:latest